### PR TITLE
use version 0.6.2

### PR DESCRIPTION
**Pull request by si458**
currently the is bug with the release candiate, so its best to use an old version until its a new version is released

also saves time having to not rebuild every single time the `latest` gets updated!

### CODE REVIEW

**Comment by dm82m** [comment]
Can you please update version within build and shell file into this commit?

**Comment by si458** [comment]
@dm82m done! sorry to nag, the `latest` was just bugging me until i realised its the release candidate version thats at fault!

maybe you could do another folder for a `dev` build which uses the `latest` image instead? would you like me to fo this?

**Comment by dm82m** [comment]
I personally don’t need it. If you need it you can for sure create a pull request.

**Comment by si458** [comment]
@dm82m FINALLY GOT THERE! #27
STUPID CODESPACES KEPT COMMITING STUFF IT SHOULDNT BE

**Comment by dm82m** [comment]
Will check it tomorrow, not at home and only my mobile with me.

**Pull request merged**
